id: PE53C30FE
initial_creation_type: input
source_metadata:
  title: Rigdzin Nyima Drakpa
  language: it
  description: 'Texts by and about the treasure-revealer Rigdzin Nyima Drakpa (rig
    ''dzin nyi ma grags pa, 1647–1710), alias Garwang Drodül Lingpa:'
  volume:
    6b641b44a2294821bc9ed195442c8f2a:
      title: 'Marmé Mönlam: The Light Offering Prayer'
      parent: Aspiration Prayers
created_at: '2022-03-01T01:22:35.009153'
last_modified_at: '2022-03-01T01:22:35.009156'
